# Generated by Django 3.2.9 on 2022-10-18 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('contact_number', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'website',
            },
        ),
    ]
