# Generated by Django 3.2.9 on 2021-12-03 09:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_userforeignkey.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0022_alter_partclassification_is_optional'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_id', models.CharField(max_length=255)),
                ('answer', models.JSONField()),
                ('quantity', models.FloatField()),
                ('type', models.CharField(choices=[('JANUARY', 'January'), ('FEBRUARY', 'February'), ('MARCH', 'March'), ('DECEMBER', 'December')], max_length=10)),
                ('created_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_order_related', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.part')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
