# Generated by Django 3.2.9 on 2021-12-03 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='type',
            field=models.CharField(choices=[('query', 'Query'), ('quote', 'Quote')], max_length=10),
        ),
    ]
