# Generated by Django 3.2.9 on 2021-12-06 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_order_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='comment',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='contact_info',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
    ]
