# Generated by Django 4.0 on 2021-12-16 07:04

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0029_remove_part_supplier_partsupplier'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authentication', '0006_delete_userrole'),
        ('order', '0008_alter_order_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order',
            new_name='Request',
        ),
    ]
