# Generated by Django 4.0 on 2021-12-17 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_rename_order_request'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestHistory',
            fields=[
                ('request_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='order.request')),
            ],
            options={
                'abstract': False,
            },
            bases=('order.request',),
        ),
        migrations.AlterField(
            model_name='request',
            name='order_id',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
    ]
