# Generated by Django 4.0 on 2021-12-17 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_requesthistory_alter_request_order_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RequestHistory',
        ),
    ]
