# Generated by Django 4.0 on 2021-12-20 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0014_requestreview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestreview',
            name='order_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.request'),
        ),
    ]
