# Generated by Django 4.0 on 2021-12-20 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0015_alter_requestreview_order_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requestreview',
            old_name='order_id',
            new_name='order',
        ),
        migrations.RemoveField(
            model_name='requestreview',
            name='file',
        ),
        migrations.AddField(
            model_name='requestreview',
            name='attachment',
            field=models.FileField(help_text='PDF file ', null=True, upload_to=''),
        ),
    ]
