# Generated by Django 4.0 on 2021-12-20 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0017_alter_requestreview_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestreview',
            name='attachment',
            field=models.FileField(help_text='Allow PDF file only', upload_to=''),
        ),
    ]
