# Generated by Django 4.0 on 2021-12-22 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0023_remove_selectedrequestreview_review_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selectedrequestreview',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.requestreview'),
        ),
    ]
