# Generated by Django 4.0 on 2021-12-22 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0024_alter_selectedrequestreview_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selectedrequestreview',
            name='review',
        ),
    ]
