# Generated by Django 4.0 on 2021-12-22 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0025_remove_selectedrequestreview_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='selectedrequestreview',
            name='review',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='order.requestreview'),
        ),
    ]
