# Generated by Django 4.0 on 2021-12-22 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0027_alter_selectedrequestreview_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selectedrequestreview',
            name='review',
        ),
        migrations.AddField(
            model_name='selectedrequestreview',
            name='review',
            field=models.ManyToManyField(to='order.RequestReview'),
        ),
    ]
