# Generated by Django 4.0 on 2021-12-27 08:14

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0029_request_modified_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestreview',
            name='attachment',
        ),
        migrations.CreateModel(
            name='RequstReviewAttachments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(help_text='Allow PDF file only', upload_to='', validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('request_review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.requestreview')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
