# Generated by Django 4.0 on 2021-12-27 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0030_remove_requestreview_attachment_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RequstReviewAttachments',
            new_name='RequstReviewAttachment',
        ),
    ]
