# Generated by Django 4.0 on 2021-12-28 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0032_request_cost_request_lead_time_requesthistory_cost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='lead_time',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='requesthistory',
            name='lead_time',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
