# Generated by Django 3.2.10 on 2021-12-29 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0033_alter_request_lead_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='is_estimated',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='requesthistory',
            name='is_estimated',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
