# Generated by Django 3.2.10 on 2021-12-29 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0034_auto_20211229_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='ref_request',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='requesthistory',
            name='ref_request',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
