# Generated by Django 4.0 on 2021-12-30 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0035_auto_20211229_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='lead_time',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='requesthistory',
            name='lead_time',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
