# Generated by Django 3.2.10 on 2022-01-05 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0037_billingaddress_orderinfo_shippingaddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='payment_method',
            field=models.CharField(choices=[('debit', 'Debit'), ('credit', 'Credit')], max_length=10),
        ),
    ]
