# Generated by Django 3.2.10 on 2022-01-06 10:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_userforeignkey.models.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0039_auto_20220106_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderinfo',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='OrderInfoHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_id', models.CharField(blank=True, max_length=255, unique=True)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=5)),
                ('total', models.DecimalField(decimal_places=2, max_digits=5)),
                ('tax', models.DecimalField(decimal_places=2, max_digits=5)),
                ('payment_method', models.CharField(choices=[('debit', 'Debit'), ('credit', 'Credit')], max_length=10)),
                ('quantity', models.FloatField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_review', 'In Review'), ('accepted', 'Accepted'), ('completed', 'Completed')], default='pending', max_length=50)),
                ('billing_address', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='order.billingaddress')),
                ('created_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_orderinfohistory_related', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='order.request')),
                ('shipping_address', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='order.shippingaddress')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
