# Generated by Django 3.2.10 on 2022-01-06 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0041_auto_20220106_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderinfo',
            name='modified_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orderinfohistory',
            name='modified_number',
            field=models.IntegerField(default=0),
        ),
    ]
