# Generated by Django 3.2.10 on 2022-01-07 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0042_auto_20220106_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='order_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='orderinfohistory',
            name='order_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
