# Generated by Django 3.2.10 on 2022-01-07 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0043_auto_20220107_1310'),
        ('order', '0043_requestreview_is_deleted_and_more'),
    ]

    operations = [
    ]
