# Generated by Django 4.0 on 2022-01-10 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0044_merge_20220107_2041'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestreview',
            name='cost',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requestreview',
            name='lead_time',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='requestreview',
            name='quantity',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
