# Generated by Django 4.0 on 2022-01-10 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0045_requestreview_cost_requestreview_lead_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestreview',
            name='cost',
            field=models.FloatField(default=12, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='requestreview',
            name='lead_time',
            field=models.CharField(default='1 days', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='requestreview',
            name='quantity',
            field=models.FloatField(default=12),
            preserve_default=False,
        ),
    ]
