# Generated by Django 3.2.10 on 2022-01-11 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0046_alter_requestreview_cost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='tax',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='orderinfohistory',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='orderinfohistory',
            name='tax',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='orderinfohistory',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
    ]
