# Generated by Django 3.2.10 on 2022-01-11 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0047_auto_20220111_1913'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderinfo',
            name='review',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='order.requestreview'),
        ),
        migrations.AddField(
            model_name='orderinfohistory',
            name='review',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='order.requestreview'),
        ),
    ]
