# Generated by Django 3.2.10 on 2022-01-12 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0048_auto_20220111_1919'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestreview',
            name='unit',
            field=models.CharField(blank=True, choices=[('day', 'Day'), ('week', 'Week'), ('month', 'Month')], max_length=255, null=True),
        ),
    ]
