# Generated by Django 3.2.10 on 2022-01-12 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0049_requestreview_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestreview',
            name='lead_time',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='requestreview',
            name='unit',
            field=models.CharField(choices=[('day', 'Day'), ('week', 'Week'), ('month', 'Month')], default=1, max_length=255),
            preserve_default=False,
        ),
    ]
