# Generated by Django 3.2.10 on 2022-01-12 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0051_auto_20220112_1847'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='review_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requesthistory',
            name='review_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
