# Generated by Django 3.2.10 on 2022-01-12 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0052_auto_20220112_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingaddress',
            name='phone_no',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='phone_no',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
