# Generated by Django 3.2.10 on 2022-01-18 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0053_auto_20220112_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestreview',
            name='unit',
            field=models.CharField(choices=[('day', 'Day'), ('week', 'Week'), ('month', 'Month')], default='day', max_length=255),
        ),
    ]
