# Generated by Django 4.0.1 on 2022-01-17 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0053_auto_20220112_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='requesthistory',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
