# Generated by Django 4.0 on 2022-01-14 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0054_request_admin_status_request_customer_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_review', 'In Review'), ('accepted', 'Accepted'), ('completed', 'Completed')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='requesthistory',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_review', 'In Review'), ('accepted', 'Accepted'), ('completed', 'Completed')], default='pending', max_length=50),
        ),
    ]
