# Generated by Django 4.0 on 2022-01-14 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0055_alter_request_status_alter_requesthistory_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='supploer_status',
            new_name='supplier_status',
        ),
        migrations.RenameField(
            model_name='requesthistory',
            old_name='supploer_status',
            new_name='supplier_status',
        ),
    ]
