# Generated by Django 4.0 on 2022-01-14 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0056_rename_supploer_status_request_supplier_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='status',
        ),
        migrations.RemoveField(
            model_name='requesthistory',
            name='status',
        ),
        migrations.AlterField(
            model_name='request',
            name='admin_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_review', 'In Review'), ('supplier_sent_review', 'Supplier Sent Review'), ('sent_review_to_customer', 'Sent Review to Customer'), ('review_submitted', 'Review submitted'), ('submitted', 'Submitted'), ('cancelled', 'Cancelled')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='request',
            name='customer_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_review', 'In Review'), ('supplier_sent_review', 'Supplier Sent Review'), ('sent_review_to_customer', 'Sent Review to Customer'), ('review_submitted', 'Review submitted'), ('submitted', 'Submitted'), ('cancelled', 'Cancelled')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='request',
            name='supplier_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_review', 'In Review'), ('supplier_sent_review', 'Supplier Sent Review'), ('sent_review_to_customer', 'Sent Review to Customer'), ('review_submitted', 'Review submitted'), ('submitted', 'Submitted'), ('cancelled', 'Cancelled')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='requesthistory',
            name='admin_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_review', 'In Review'), ('supplier_sent_review', 'Supplier Sent Review'), ('sent_review_to_customer', 'Sent Review to Customer'), ('review_submitted', 'Review submitted'), ('submitted', 'Submitted'), ('cancelled', 'Cancelled')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='requesthistory',
            name='customer_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_review', 'In Review'), ('supplier_sent_review', 'Supplier Sent Review'), ('sent_review_to_customer', 'Sent Review to Customer'), ('review_submitted', 'Review submitted'), ('submitted', 'Submitted'), ('cancelled', 'Cancelled')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='requesthistory',
            name='supplier_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_review', 'In Review'), ('supplier_sent_review', 'Supplier Sent Review'), ('sent_review_to_customer', 'Sent Review to Customer'), ('review_submitted', 'Review submitted'), ('submitted', 'Submitted'), ('cancelled', 'Cancelled')], default='pending', max_length=50),
        ),
    ]
