# Generated by Django 3.2.10 on 2022-01-18 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0054_alter_requestreview_unit'),
        ('order', '0057_remove_request_status_remove_requesthistory_status_and_more'),
    ]

    operations = [
    ]
