# Generated by Django 3.2.10 on 2022-01-18 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0054_alter_request_quantity_alter_requesthistory_quantity'),
        ('order', '0058_merge_20220118_1733'),
    ]

    operations = [
    ]
