# Generated by Django 3.2.10 on 2022-01-19 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0059_merge_20220118_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestreview',
            name='admin_cost',
            field=models.FloatField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requestreview',
            name='admin_lead_time',
            field=models.FloatField(default=2),
            preserve_default=False,
        ),
    ]
