# Generated by Django 3.2.9 on 2022-01-19 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0059_merge_20220118_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderinfo',
            name='payment_info',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderinfohistory',
            name='payment_info',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
