# Generated by Django 3.2.9 on 2022-01-20 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0060_auto_20220119_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='payment_method',
            field=models.CharField(choices=[('strip', 'Strip')], max_length=10),
        ),
        migrations.AlterField(
            model_name='orderinfohistory',
            name='payment_method',
            field=models.CharField(choices=[('strip', 'Strip')], max_length=10),
        ),
    ]
