# Generated by Django 3.2.10 on 2022-01-19 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0060_auto_20220119_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestreview',
            name='admin_cost',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='requestreview',
            name='admin_lead_time',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
