# Generated by Django 3.2.10 on 2022-01-19 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0061_auto_20220119_1814'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requestreview',
            old_name='admin_cost',
            new_name='supplier_cost',
        ),
        migrations.RenameField(
            model_name='requestreview',
            old_name='admin_lead_time',
            new_name='supplier_lead_time',
        ),
    ]
