# Generated by Django 3.2.10 on 2022-01-19 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0064_auto_20220119_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestreview',
            name='supplier_unit',
            field=models.CharField(choices=[('day', 'Day'), ('week', 'Week'), ('month', 'Month')], default='day', max_length=255),
        ),
    ]
