# Generated by Django 3.2.10 on 2022-01-19 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0065_requestreview_supplier_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestreview',
            name='cost_unit',
            field=models.CharField(choices=[('EUR', '€-EUR'), ('USD', '$-USD'), ('CNY', '¥-CNY')], default='$', max_length=10),
        ),
        migrations.AddField(
            model_name='requestreview',
            name='supplier_cost_unit',
            field=models.CharField(choices=[('EUR', '€-EUR'), ('USD', '$-USD'), ('CNY', '¥-CNY')], default='$', max_length=10),
        ),
    ]
