# Generated by Django 3.2.9 on 2022-01-20 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0062_auto_20220120_1028'),
        ('order', '0067_alter_requestreview_supplier_cost_unit'),
    ]

    operations = [
    ]
