# Generated by Django 3.2.10 on 2022-01-20 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0067_alter_requestreview_supplier_cost_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestreview',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
    ]
