# Generated by Django 3.2.10 on 2022-01-20 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0068_alter_requestreview_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestreview',
            name='cost_unit',
            field=models.CharField(choices=[('EUR', '€-EUR'), ('USD', '$-USD'), ('CNY', '¥-CNY')], default='USD', max_length=10),
        ),
    ]
