# Generated by Django 3.2.10 on 2022-01-20 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0069_alter_requestreview_cost_unit'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='requestreview',
            constraint=models.CheckConstraint(check=models.Q(('cost__gt', '0.0')), name='cost_gt_0'),
        ),
    ]
