# Generated by Django 3.2.10 on 2022-01-20 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0070_requestreview_cost_gt_0'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='requestreview',
            constraint=models.CheckConstraint(check=models.Q(('supplier_cost__gt', '0.0')), name='supplier_cost_gt_0'),
        ),
    ]
