# Generated by Django 3.2.10 on 2022-01-20 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0071_requestreview_supplier_cost_gt_0'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='requestreview',
            constraint=models.CheckConstraint(check=models.Q(('lead_time__gt', '0.0')), name='lead_time_gt_0'),
        ),
        migrations.AddConstraint(
            model_name='requestreview',
            constraint=models.CheckConstraint(check=models.Q(('supplier_lead_time__gt', '0.0')), name='supplier_lead_time_gt_0'),
        ),
    ]
