# Generated by Django 3.2.9 on 2022-01-21 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0068_merge_20220120_1116'),
        ('order', '0072_auto_20220120_1732'),
    ]

    operations = [
    ]
