# Generated by Django 3.2.11 on 2022-01-24 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0073_merge_20220121_1224'),
        ('order', '0076_auto_20220121_1114'),
    ]

    operations = [
    ]
