# Generated by Django 3.2.11 on 2022-01-26 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0077_merge_20220124_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requstreviewattachment',
            name='request_review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='order.requestreview'),
        ),
    ]
