# Generated by Django 3.2.11 on 2022-01-26 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0078_alter_requstreviewattachment_request_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='moderator_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('in_review', 'In Review'), ('sent_to_supplier', 'Sent to supplier'), ('processing', 'Processing'), ('new_request', 'New request'), ('received_results_from_supplier', 'Received results from supplier'), ('new_review', 'New review'), ('competed', 'Competed'), ('results', 'Results'), ('submitted', 'Submitted'), ('cancelled', 'Cancelled')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='requesthistory',
            name='moderator_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('in_review', 'In Review'), ('sent_to_supplier', 'Sent to supplier'), ('processing', 'Processing'), ('new_request', 'New request'), ('received_results_from_supplier', 'Received results from supplier'), ('new_review', 'New review'), ('competed', 'Competed'), ('results', 'Results'), ('submitted', 'Submitted'), ('cancelled', 'Cancelled')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='admin_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('in_review', 'In Review'), ('sent_to_supplier', 'Sent to supplier'), ('processing', 'Processing'), ('new_request', 'New request'), ('received_results_from_supplier', 'Received results from supplier'), ('new_review', 'New review'), ('competed', 'Competed'), ('results', 'Results'), ('submitted', 'Submitted'), ('cancelled', 'Cancelled')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='customer_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('in_review', 'In Review'), ('sent_to_supplier', 'Sent to supplier'), ('processing', 'Processing'), ('new_request', 'New request'), ('received_results_from_supplier', 'Received results from supplier'), ('new_review', 'New review'), ('competed', 'Competed'), ('results', 'Results'), ('submitted', 'Submitted'), ('cancelled', 'Cancelled')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='supplier_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('in_review', 'In Review'), ('sent_to_supplier', 'Sent to supplier'), ('processing', 'Processing'), ('new_request', 'New request'), ('received_results_from_supplier', 'Received results from supplier'), ('new_review', 'New review'), ('competed', 'Competed'), ('results', 'Results'), ('submitted', 'Submitted'), ('cancelled', 'Cancelled')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='requesthistory',
            name='admin_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('in_review', 'In Review'), ('sent_to_supplier', 'Sent to supplier'), ('processing', 'Processing'), ('new_request', 'New request'), ('received_results_from_supplier', 'Received results from supplier'), ('new_review', 'New review'), ('competed', 'Competed'), ('results', 'Results'), ('submitted', 'Submitted'), ('cancelled', 'Cancelled')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='requesthistory',
            name='customer_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('in_review', 'In Review'), ('sent_to_supplier', 'Sent to supplier'), ('processing', 'Processing'), ('new_request', 'New request'), ('received_results_from_supplier', 'Received results from supplier'), ('new_review', 'New review'), ('competed', 'Competed'), ('results', 'Results'), ('submitted', 'Submitted'), ('cancelled', 'Cancelled')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='requesthistory',
            name='supplier_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('in_review', 'In Review'), ('sent_to_supplier', 'Sent to supplier'), ('processing', 'Processing'), ('new_request', 'New request'), ('received_results_from_supplier', 'Received results from supplier'), ('new_review', 'New review'), ('competed', 'Competed'), ('results', 'Results'), ('submitted', 'Submitted'), ('cancelled', 'Cancelled')], max_length=50, null=True),
        ),
    ]
