# Generated by Django 3.2.11 on 2022-02-03 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0086_auto_20220203_1838'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='zip_code',
        ),
        migrations.RemoveField(
            model_name='requesthistory',
            name='zip_code',
        ),
    ]
