# Generated by Django 3.2.11 on 2022-02-10 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0086_auto_20220204_1141'),
        ('order', '0087_auto_20220203_1847'),
    ]

    operations = [
    ]
