# Generated by Django 3.2.11 on 2022-02-25 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0088_merge_0086_auto_20220204_1141_0087_auto_20220203_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='requesthistory',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
    ]
