# Generated by Django 4.1.2 on 2022-10-26 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0089_auto_20220225_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='image_comment',
            field=models.ImageField(blank=True, null=True, upload_to='static/post/'),
        ),
        migrations.AddField(
            model_name='requesthistory',
            name='image_comment',
            field=models.ImageField(blank=True, null=True, upload_to='static/post/'),
        ),
    ]
