# Generated by Django 4.2 on 2024-09-29 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0091_alter_request_image_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='image_comment',
            field=models.FileField(blank=True, null=True, upload_to='media/post/'),
        ),
        migrations.AlterField(
            model_name='requesthistory',
            name='image_comment',
            field=models.FileField(blank=True, null=True, upload_to='media/post/'),
        ),
    ]
