# Generated by Django 3.2.9 on 2021-11-22 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0001_initial'),
        ('product', '0003_attribute_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attribute',
            name='unit',
        ),
        migrations.AddField(
            model_name='attribute',
            name='unit',
            field=models.ManyToManyField(to='utils.Unit'),
        ),
    ]
