# Generated by Django 3.2.9 on 2021-11-22 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0001_initial'),
        ('product', '0006_alter_attribute_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attribute',
            name='unit',
        ),
        migrations.AddField(
            model_name='attribute',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='utils.unit'),
        ),
    ]
