# Generated by Django 3.2.9 on 2021-11-22 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_part'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='part',
            name='classification',
        ),
        migrations.AddField(
            model_name='part',
            name='classification',
            field=models.ManyToManyField(to='product.Classification'),
        ),
    ]
