# Generated by Django 3.2.9 on 2021-11-30 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_partclassification_partclassificationattribute'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
