# Generated by Django 3.2.9 on 2021-11-30 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_part_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partclassification',
            name='classification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classifications', to='product.classification'),
        ),
    ]
