# Generated by Django 3.2.9 on 2021-12-02 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_rename_is_required_partclassification_is_optional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partclassification',
            name='is_optional',
            field=models.CharField(blank=True, default=False, max_length=255),
        ),
    ]
