# Generated by Django 3.2.9 on 2021-12-02 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_alter_partclassification_is_optional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partclassification',
            name='is_optional',
            field=models.CharField(blank=True, default=False, max_length=255, null=True),
        ),
    ]
