# Generated by Django 3.2.9 on 2021-12-03 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0022_alter_partclassification_is_optional'),
        ('product', '0022_auto_20211202_0735'),
    ]

    operations = [
    ]
