# Generated by Django 3.2.9 on 2021-12-06 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0023_merge_20211203_1431'),
        ('product', '0023_merge_20211203_1514'),
    ]

    operations = [
    ]
