# Generated by Django 3.2.9 on 2021-12-10 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0024_alter_attribute_created_by_remove_attribute_unit_and_more'),
        ('product', '0024_merge_20211206_1548'),
    ]

    operations = [
    ]
