# Generated by Django 4.0 on 2021-12-13 07:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0002_alter_unit_created_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0024_alter_attribute_created_by_remove_attribute_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='supplier',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='unit',
            field=models.ManyToManyField(blank=True, to='utils.Unit'),
        ),
    ]
