# Generated by Django 3.2.9 on 2021-12-13 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0002_alter_unit_created_by'),
        ('product', '0024_alter_attribute_created_by_remove_attribute_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='unit',
            field=models.ManyToManyField(blank=True, to='utils.Unit'),
        ),
    ]
