# Generated by Django 3.2.9 on 2021-12-14 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0025_alter_attribute_unit'),
        ('product', '0025_part_supplier_alter_attribute_unit'),
    ]

    operations = [
    ]
