# Generated by Django 4.0 on 2021-12-17 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        # ('product', '0025_merge_20211210_1406'),
        ('product', '0029_remove_part_supplier_partsupplier'),
    ]

    operations = [
    ]
