# Generated by Django 3.2.10 on 2021-12-24 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0030_merge_20211217_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classification',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
