# Generated by Django 4.0 on 2022-01-05 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0025_merge_20211210_1406'),
        ('product', '0031_alter_classification_title'),
    ]

    operations = [
    ]
