# Generated by Django 4.0 on 2021-12-15 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('moderator', 'moderator'), ('supplier', 'supplier'), ('customer', 'customer')], default='super_admin', max_length=50, null=True),
        ),
    ]
