# Generated by Django 4.0 on 2021-12-15 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('moderator', 'moderator'), ('supplier', 'supplier'), ('customer', 'customer')], max_length=50, null=True),
        ),
    ]
