# Generated by Django 4.0.2 on 2022-02-28 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_pageseo_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='page_seo',
            field=models.ManyToManyField(blank=True, null=True, to='authentication.PageSEO'),
        ),
    ]
