# Generated by Django 4.0.2 on 2022-02-28 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_alter_page_page_seo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Page',
        ),
        migrations.DeleteModel(
            name='PageSEO',
        ),
    ]
