# Generated by Django 4.0.2 on 2022-02-28 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_alter_userprofile_file'),
        ('authentication', '0011_delete_page_delete_pageseo'),
    ]

    operations = [
    ]
