# Generated by Django 4.0.2 on 2022-03-01 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_merge_20220228_1949'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
